openapi: 3.0.3
tags: []
info:
  title: CMU Dining API
  description: Development documentation
  version: 2.0.0
paths:
  /login:
    get:
      parameters:
        - name: redirectURL
          in: query
          required: true
          schema:
            nullable: true
            anyOf:
              - type: string
              - type: "null"
      operationId: getLogin
  /logout:
    get:
      parameters:
        - name: redirectURL
          in: query
          required: true
          schema:
            nullable: true
            anyOf:
              - type: string
              - type: "null"
      operationId: getLogout
  /code-exchange:
    get:
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
      operationId: getCode-exchange
  /:
    get:
      responses:
        "200":
          description: Response for status 200
          content:
            text/plain:
              schema:
                examples:
                  - ScottyLabs Dining API
                type: string
      operationId: getIndex
  /v2/locations:
    get:
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    times:
                      type: array
                      items:
                        type: object
                        properties:
                          start:
                            examples:
                              - 1766976342183
                            type: number
                          end:
                            examples:
                              - 1766976342183
                            type: number
                        required:
                          - start
                          - end
                    todaysSoups:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                        required:
                          - name
                          - description
                    todaysSpecials:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                        required:
                          - name
                          - description
                    name:
                      nullable: true
                      anyOf:
                        - examples:
                            - Schatz
                          type: string
                        - type: "null"
                    location:
                      type: string
                    shortDescription:
                      nullable: true
                      anyOf:
                        - type: string
                        - type: "null"
                    description:
                      type: string
                    url:
                      type: string
                    menu:
                      nullable: true
                      anyOf:
                        - type: string
                        - type: "null"
                    coordinateLat:
                      nullable: true
                      anyOf:
                        - type: number
                        - type: "null"
                    coordinateLng:
                      nullable: true
                      anyOf:
                        - type: number
                        - type: "null"
                    acceptsOnlineOrders:
                      type: boolean
                    id:
                      type: string
                    conceptId:
                      nullable: true
                      anyOf:
                        - type: string
                        - type: "null"
                  required:
                    - times
                    - todaysSoups
                    - todaysSpecials
                    - name
                    - location
                    - shortDescription
                    - description
                    - url
                    - menu
                    - coordinateLat
                    - coordinateLng
                    - acceptsOnlineOrders
                    - id
                    - conceptId
      operationId: getV2Locations
  /emails:
    get:
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      example:
                        - Alice
                      type: string
                    email:
                      example: alice72@andrew.cmu.edu
                      type: string
                  required:
                    - name
                    - email
      operationId: getEmails
  /sendSlackMessage:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
          multipart/form-data:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      operationId: postSendSlackMessage
  /whoami:
    get:
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    nullable: true
                    anyOf:
                      - type: object
                        properties:
                          googleId:
                            type: string
                          id:
                            type: number
                          email:
                            type: string
                          firstName:
                            nullable: true
                            anyOf:
                              - type: string
                              - type: "null"
                          lastName:
                            nullable: true
                            anyOf:
                              - type: string
                              - type: "null"
                          pictureUrl:
                            nullable: true
                            anyOf:
                              - type: string
                              - type: "null"
                        required:
                          - googleId
                          - id
                          - email
                          - firstName
                          - lastName
                          - pictureUrl
                      - type: "null"
                required:
                  - user
                additionalProperties: false
      operationId: getWhoami
components:
  schemas: {}
