openapi: 3.0.3
tags: []
info:
  title: CMU Dining API
  description: Hello!~ Thanks for checking out the cmueats api. Have a great day!
  version: 2.0.0
paths:
  /whoami:
    get:
      description: If you have an active login session with cmueats, this will return
        your user info. (this is NOT intended to work cross-site)
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    nullable: true
                    anyOf:
                      - type: object
                        properties:
                          googleId:
                            type: string
                          id:
                            type: number
                          email:
                            type: string
                          firstName:
                            nullable: true
                            anyOf:
                              - type: string
                              - type: "null"
                          lastName:
                            nullable: true
                            anyOf:
                              - type: string
                              - type: "null"
                          pictureUrl:
                            nullable: true
                            anyOf:
                              - type: string
                              - type: "null"
                        required:
                          - googleId
                          - id
                          - email
                          - firstName
                          - lastName
                          - pictureUrl
                      - type: "null"
                required:
                  - user
                additionalProperties: false
      operationId: getWhoami
  /:
    get:
      responses:
        "200":
          description: Response for status 200
          content:
            text/plain:
              schema:
                examples:
                  - ScottyLabs Dining API
                type: string
      operationId: getIndex
  /v2/locations:
    get:
      description: The times array is guaranteed to be sorted and non-overlapping.
        Both start and end are inclusive boundaries
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    times:
                      type: array
                      items:
                        type: object
                        properties:
                          start:
                            examples:
                              - 1771392122322
                            type: number
                          end:
                            examples:
                              - 1771392122322
                            type: number
                        required:
                          - start
                          - end
                    todaysSoups:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                        required:
                          - name
                          - description
                    todaysSpecials:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                        required:
                          - name
                          - description
                    name:
                      nullable: true
                      anyOf:
                        - examples:
                            - Schatz
                          type: string
                        - type: "null"
                    location:
                      type: string
                    ratingsAvg:
                      nullable: true
                      anyOf:
                        - type: number
                        - type: "null"
                    ratingsCount:
                      type: number
                    shortDescription:
                      nullable: true
                      anyOf:
                        - type: string
                        - type: "null"
                    description:
                      type: string
                    url:
                      type: string
                    menu:
                      nullable: true
                      anyOf:
                        - type: string
                        - type: "null"
                    coordinateLat:
                      nullable: true
                      anyOf:
                        - type: number
                        - type: "null"
                    coordinateLng:
                      nullable: true
                      anyOf:
                        - type: number
                        - type: "null"
                    acceptsOnlineOrders:
                      type: boolean
                    id:
                      type: string
                    conceptId:
                      nullable: true
                      anyOf:
                        - type: string
                        - type: "null"
                  required:
                    - times
                    - todaysSoups
                    - todaysSpecials
                    - name
                    - location
                    - ratingsAvg
                    - ratingsCount
                    - shortDescription
                    - description
                    - url
                    - menu
                    - coordinateLat
                    - coordinateLng
                    - acceptsOnlineOrders
                    - id
                    - conceptId
      operationId: getV2Locations
  /emails:
    get:
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      example: Alice
                      type: string
                    email:
                      example: alice72@andrew.cmu.edu
                      type: string
                  required:
                    - name
                    - email
      operationId: getEmails
  /report:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                locationName:
                  type: string
                locationId:
                  type: string
                message:
                  maxLength: 300
                  type: string
              required:
                - locationName
                - locationId
                - message
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                locationName:
                  type: string
                locationId:
                  type: string
                message:
                  maxLength: 300
                  type: string
              required:
                - locationName
                - locationId
                - message
          multipart/form-data:
            schema:
              type: object
              properties:
                locationName:
                  type: string
                locationId:
                  type: string
                message:
                  maxLength: 300
                  type: string
              required:
                - locationName
                - locationId
                - message
      operationId: postReport
  /v2/locations/{locationId}/reviews/summary:
    get:
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  starData:
                    type: object
                    properties:
                      avg:
                        nullable: true
                        anyOf:
                          - type: number
                          - type: "null"
                      personalRating:
                        nullable: true
                        anyOf:
                          - type: number
                          - type: "null"
                      buckets:
                        example:
                          - 0
                          - 1
                          - 0
                          - 4
                          - 12
                          - 4
                        description: Count of ratings of star rating
                          [{.5},{1,1.5},{2,2.5},{3,3.5},{4,4.5},{5}]
                        type: array
                        items:
                          type: number
                    required:
                      - avg
                      - personalRating
                      - buckets
                  tagData:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        totalVotes:
                          type: number
                        totalLikes:
                          type: number
                        myReview:
                          nullable: true
                          anyOf:
                            - type: object
                              properties:
                                vote:
                                  type: boolean
                                text:
                                  nullable: true
                                  anyOf:
                                    - type: string
                                    - type: "null"
                                createdAt:
                                  type: number
                                updatedAt:
                                  type: number
                              required:
                                - vote
                                - text
                                - createdAt
                                - updatedAt
                            - type: "null"
                      required:
                        - id
                        - name
                        - totalVotes
                        - totalLikes
                        - myReview
                required:
                  - starData
                  - tagData
                additionalProperties: false
      operationId: getV2LocationsByLocationIdReviewsSummary
  /v2/locations/{locationId}/reviews/stars/me:
    put:
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                stars:
                  minimum: 0.5
                  maximum: 5
                  multipleOf: 0.5
                  type: number
              required:
                - stars
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                stars:
                  minimum: 0.5
                  maximum: 5
                  multipleOf: 0.5
                  type: number
              required:
                - stars
          multipart/form-data:
            schema:
              type: object
              properties:
                stars:
                  minimum: 0.5
                  maximum: 5
                  multipleOf: 0.5
                  type: number
              required:
                - stars
      operationId: putV2LocationsByLocationIdReviewsStarsMe
    delete:
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: string
      operationId: deleteV2LocationsByLocationIdReviewsStarsMe
  /v2/locations/{locationId}/reviews/tags/{tagId}/me:
    put:
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: string
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voteUp:
                  nullable: true
                  anyOf:
                    - type: boolean
                    - type: "null"
                text:
                  nullable: true
                  anyOf:
                    - maxLength: 1000
                      type: string
                    - type: "null"
              required:
                - voteUp
                - text
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                voteUp:
                  nullable: true
                  anyOf:
                    - type: boolean
                    - type: "null"
                text:
                  nullable: true
                  anyOf:
                    - maxLength: 1000
                      type: string
                    - type: "null"
              required:
                - voteUp
                - text
          multipart/form-data:
            schema:
              type: object
              properties:
                voteUp:
                  nullable: true
                  anyOf:
                    - type: boolean
                    - type: "null"
                text:
                  nullable: true
                  anyOf:
                    - maxLength: 1000
                      type: string
                    - type: "null"
              required:
                - voteUp
                - text
      operationId: putV2LocationsByLocationIdReviewsTagsByTagIdMe
  /v2/locations/{locationId}/reviews/tags:
    get:
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    writtenReview:
                      type: string
                    tagName:
                      type: string
                    id:
                      type: number
                    tagId:
                      type: number
                    userId:
                      type: number
                    locationId:
                      type: string
                    vote:
                      type: boolean
                    createdAt:
                      type: number
                    updatedAt:
                      type: number
                  required:
                    - writtenReview
                    - tagName
                    - id
                    - tagId
                    - userId
                    - locationId
                    - vote
                    - createdAt
                    - updatedAt
      operationId: getV2LocationsByLocationIdReviewsTags
components:
  schemas: {}

