import assert from './assert';
import bounded from './misc';

const graveyard = [
	'Staying up all night?',
	'Want a late-night snack?',
	"Don't stay up too late!",
	'Delivery too expensive?',
	'Pulling an all-nighter? Let us fuel your focus!',
	'When the world sleeps, your snack game is strong!',
	'Late night genius? Keep it going with a bite!',
	'Need a boost for your midnight grind?',
	"It's quiet, but your cravings aren't—time for a snack!",
	"Midnight snack attack? We've got the fix!",
	'The stars are out, and so are the snacks!',
	'Awake while others dream? Power up with a late-night bite!',
	'The night is still, but your hunger is alive—let us satisfy your cravings.',
	'Under the moonlight, every bite is a midnight delight.',
	'As the world dreams, let us awaken your taste buds.',
	'In the silence of the night, find your perfect midnight snack.',
	"Stars above, a snack below—let's make the night magical.",
	'In the quiet hours, let every bite be a whisper of comfort.',
	"The moon may shine, but your cravings glow brighter—let's indulge.",
	'When the night is deep, let us serve something to keep you going.',
	'In the stillness of the night, let your cravings whisper to the stars.',
	'Where the darkness is endless, let your meal be a spark of joy.',
	'In the quiet of midnight, your hunger calls—let us answer softly.',
	'When the world sleeps, let your senses awaken to something extraordinary.',
	'The night wraps around you like a dream—let us offer a taste to match its beauty.',
	'A moment in the moonlight, a bite to soothe your soul.',
	'In the shadows of the night, let your hunger find solace in every flavor.',
	'In the hush of the night, let your hunger find solace in every sweet bite.',
	'As the moon watches over, let your meal be a quiet dance of flavors.',
	'The stars write stories, and tonight, your meal is the chapter that nourishes your soul.',
	'Let the cool night breeze guide you to a feast made for midnight dreamers.',
	'Under the canvas of night, let each taste paint a picture of comfort and delight.',
	'As darkness falls, let your meal be the beacon that lights your way.',
	'The night whispers mysteries—let us reveal them one delicious bite at a time.',
	'In the silence between stars, your hunger calls—let us craft a meal to answer.',
	'The moon spills whispers into the silence, her light weaving silver dreams through the night—let each bite be a spark that flickers softly.',
	'The stars blink like ancient eyes, their gaze infinite and serene—let your hunger rise like mist beneath their watchful glow.',
	'The night cradles the earth in velvet shadows, her breath cool and quiet—let every flavor bloom like a secret kept between the stars.',
	'The moon hums softly to the sleeping world, her song stitched in silver—let each taste be a thread woven into her lullaby.',
	'The darkness wraps around you like a lover’s arms, tender and deep—let each bite shimmer like a whispered promise beneath the stars.',
	'The stars hang like lanterns in the midnight sky, glowing with stories untold—let your meal be a word in the story they tell.',
	'The moon leans close, her touch a cool kiss upon the earth—let each taste rise like a sigh in the silence of night.',
	'The sky folds in upon itself, a cloak of quiet wrapped in shadow—let your hunger bloom like a hidden flower in the dark.',
	'The stars scatter like diamonds on black velvet, their light soft as a whispered prayer—let each bite glisten in the darkness like hope.',
	'The night wraps the world in velvet and silence, her embrace endless—let your cravings whisper back in harmony with her stillness.',
	'The moon dances with the clouds, her light a soft pulse upon the world—let your meal be the rhythm to which the stars sway.',
	'The darkness hums with the breath of forgotten dreams, her voice low and sweet—let each bite be a note carried on the wind.',
	'The stars paint the sky in strokes of light, delicate and endless—let your meal be the brush that completes the picture.',
	'The night speaks in quiet tones, her words spun from shadows—let your hunger answer like a soft echo in the stillness.',
	'The moon weaves her silver into the sky’s tapestry, her hands gentle—let each bite be a thread in the fabric of night.',
	'The stars write their stories in the quiet spaces of the night, their light a language of silence—let your meal be a part of their tale.',
	'The darkness whispers sweet nothings to the earth, her breath cool against your skin—let each taste bloom like a flower kissed by shadow.',
	'The stars hum softly above, their light a quiet symphony—let your hunger dance along, swaying in the rhythm of the night.',
	'The night stretches her arms wide, cradling the world in her silence—let each bite be a flame that flickers softly in her embrace.',
	'The moon gazes down with quiet love, her light a tender caress—let your meal rise like a soft prayer in her glow.',
	'The stars bow low, their light a blessing upon the earth—let your cravings bloom like flowers kissed by the midnight sky.',
	'The night holds her breath in reverence, the world wrapped in velvet—let each taste be a gentle sigh in the dark.',
	'The stars blink in quiet wonder, their gaze ancient and knowing—let each bite be a reflection of their soft glow.',
	'The night hums her soft lullaby, her song woven from shadows—let your hunger find comfort in her melody.',
	'The moon watches over the world with silvered eyes, her gaze endless—let each taste be a star in the dark expanse.',
];
const morning = [
	'Fancy some breakfast?',
	'Is breakfast really the most important meal of the day?',
	'What do you want to eat?',
	'Have a good morning!',
	'Start your day with a delicious meal!',
	'Time to refuel for the day ahead!',
	'Breakfast is calling your name!',
	"Sun's up, breakfast is served!",
	"Rise and shine, it's breakfast time!",
	'Fuel the morning hustle with something delicious!',
	'The best way to start your day? A tasty breakfast!',
	'Your morning journey starts with breakfast!',
	'The campus is waking up—join in with breakfast!',
	"Your day's first win: a perfect breakfast!",
	'Before you conquer the day, conquer breakfast!',
	'The breakfast bell is ringing—are you answering?',
	'As dawn kisses the horizon, let your meal be the first light of your day.',
	'With the sunrise comes the promise of something beautiful—let breakfast be that promise.',
	'The morning sky is painted with hope—let your breakfast be as inspiring.',
	'In the gentle glow of the morning, let your meal be a soft embrace to start your day.',
	'With each ray of sun, a new taste awaits—let breakfast be your first adventure.',
	'Morning dew and fresh beginnings—let breakfast carry you into the day with grace.',
	'Let the quiet beauty of the morning reflect in every bite you take.',
	'The world awakens softly—let your breakfast do the same, filling you with warmth.',
	'As the morning sky blushes, let your breakfast bloom with promise and joy.',
	'Like the first light of day, let your meal unfold with grace and beauty.',
	'With each sunrise, the world is reborn—let your breakfast be the start of something new.',
	'In the golden embrace of morning, let your plate be a symphony of flavors.',
	'As the sun climbs, let your spirit and hunger rise together, fed by something wonderful.',
	'Morning light and fresh beginnings—let your meal be a moment of pure poetry.',
	'The dawn breaks gently, and so does the warmth of your first bite—welcome the day with joy.',
	'Let the soft light of morning carry you to a breakfast as gentle as the breeze.',
	'The dawn spills gold like honey across the sky—let your meal catch the first light and bloom in its warmth.',
	'The sun rises slowly, painting the world in soft strokes of light—let your hunger rise like flowers opening to the day.',
	'The morning whispers across the earth, its breath cool and sweet—let each bite unfurl like petals kissed by the light.',
	'The sky blushes with the touch of the first light—let your meal blossom like a rose kissed by the dawn.',
	'Morning pours its light like a gentle stream—let your meal reflect the glow, bright and clear.',
	'The world wakes with a sigh, the light soft against the skin—let your hunger grow like sunlight reaching through the trees.',
	"The air is fresh with promise, each breeze a whispered secret—let every bite be as soft and bright as the morning's first breath.",
	'The horizon unfolds like a page written in light—let your meal be a verse in the song of a new day.',
	'The day stretches its arms wide, opening the world to light—let each taste bloom like a flower touched by the first sun.',
	'As the light reaches its fingers over the earth, let your meal unfold like a quiet promise fulfilled.',
	'The sun climbs higher, its warmth spreading across the sky—let each bite catch the glow and grow in its light.',
	'Morning hums with quiet joy, the air light with possibility—let your hunger find its place in the song.',
	"The sun's fingers trace the horizon, soft and warm—let your meal follow, bright and full of promise.",
	"The world stirs beneath the sun's touch, light blooming across the sky—let your meal rise with the morning air.",
	'The sky fills with light, each ray a breath of warmth—let your meal be the first bloom in the garden of the day.',
	'The morning stretches across the horizon, its light soft and new—let your hunger grow like a flower opening in the warmth.',
	'The light kisses the earth awake, each touch soft as a whisper—let each bite glow like the first rays of morning.',
	'The sun pours itself across the world, its light a soft invitation—let your meal answer, warm and full of promise.',
	'Morning breathes softly upon the earth, the air cool and clear—let your meal rise like a breath caught in the first light.',
	'The horizon hums with the quiet of a new day, its light spreading wide—let each taste bloom in the soft glow.',
	'The sun spills gold upon the earth, the light warm against your skin—let your hunger rise like mist touched by dawn.',
	'Morning whispers sweetly, its breath soft against the earth—let each bite be a gentle answer to the call of day.',
	'The light of morning spills across the world, filling the sky with warmth—let your meal bloom in the glow.',
	'The sun stretches over the horizon, its warmth growing brighter—let your hunger rise like flowers opening to the day.',
	'The air hums with the breath of morning, light spreading wide—let each taste catch the first glow and bloom in its warmth.',
];

const afternoon = [
	'What do you want for lunch?',
	'What do you want to eat?',
	'Have a good afternoon!',
	'Use those blocks!',
	'Fuel up for the afternoon!',
	'Lunch options galore!',
	'Satisfy your midday hunger!',
	'Craving something savory for lunch?',
	"Midday munchies? We've got you covered!",
	'Halfway through the day—time for a lunch break!',
	"What's for lunch? Let's make it awesome!",
	"The afternoon slump's no match for a great lunch!",
	'Hit reset on your day with a satisfying lunch!',
	'Midday fuel-up to keep you moving!',
	'Break away from the books—lunch awaits!',
	'Recharge with the perfect lunch combo!',
	"Afternoon cravings? Let's handle them with style!",
	'The day reaches its peak—let lunch be your pause in the whirlwind of time.',
	'As the sun reaches high, let your plate reflect the abundance of the day.',
	'The afternoon is a canvas, and your meal is the brushstroke of calm in the rush.',
	'In the warmth of the afternoon, let each flavor bloom like a flower in the sun.',
	"Let your lunch be a gentle retreat, a quiet breath amid the day's rhythm.",
	'As the day unfolds, let every bite be a reminder to savor the beauty around you.',
	'In the stillness between hours, let your meal be a moment to reflect and rejuvenate.',
	"As the sun sits high in the sky, let your meal be the calm in the midst of the day's rhythm.",
	'The afternoon glows with possibility—let your lunch be the spark that fuels your journey.',
	'Beneath the midday sun, let every bite be a reminder of the beauty in small moments.',
	'In the warmth of the afternoon, let your meal be a pause, a gentle breath between hours.',
	'The day stretches long, but let your lunch shorten the distance with a taste of joy.',
	'As time marches on, let your meal be a moment suspended in delicious peace.',
	'In the golden hours of the afternoon, let your plate be as radiant as the sun above.',
	'Let your lunch carry you like the wind—light, freeing, and full of life.',
	'The afternoon sun spills gold upon the earth, its warmth a soft embrace—let each bite bloom in the glow of its touch.',
	"The day stretches wide beneath the sun's gaze, its warmth endless—let your meal rise like a flower opening to the light.",
	'The afternoon hums with quiet joy, the air full of light—let each taste bloom like petals kissed by the sun.',
	'The sun leans low, its warmth soft against your skin—let your hunger rise like a flower reaching for the last rays of light.',
	'The day breathes deeply in the warmth, the air thick with light—let your meal bloom in the glow.',
	'The afternoon whispers softly, its breath full of sun—let your meal glow like embers touched by a gentle breeze.',
	'The sun spills light like honey, its warmth settling into the earth—let your hunger bloom in its sweetness.',
	'The afternoon stretches across the sky, the light golden and sure—let your meal rise like a flower opening in the warmth.',
	'The day wears light like a crown, its glow endless—let each taste shimmer in the warmth.',
	'The sun leans into the world, its warmth filling every corner—let your meal bloom in the glow of its touch.',
	'The sky hums with light, its song soft and golden—let your hunger bloom in the warmth of the afternoon.',
	'The afternoon breathes warmth into the world, the air full of light—let each taste bloom in the glow.',
	'The sun spills its warmth upon the earth, its light soft as a whisper—let your hunger rise like flowers kissed by the day.',
	'The afternoon stretches long, the light settling into the world—let each taste bloom in the warmth.',
	'The sun pours gold across the sky, its warmth endless—let your hunger rise like a flower opening to the touch of day.',
	'The afternoon hums with quiet joy, the air full of warmth—let each bite bloom in the golden light.',
	'The sun wears the sky like a crown, its warmth endless—let your hunger shimmer in its touch.',
	'The day leans into the warmth, the air thick with light—let your hunger bloom in the golden glow.',
	'The sun stretches across the sky, its warmth endless—let each taste bloom like petals kissed by the light.',
	'The afternoon hums softly, its warmth settling into the earth—let your meal glow in the warmth of the day.',
	"The sky wears the sun's light like a soft blanket, its warmth endless—let your hunger bloom in the golden glow.",
	'The sun spills its warmth across the earth, the light soft and full—let each taste rise like a flower kissed by the light.',
	'The afternoon whispers softly, its warmth settling into the day—let each bite bloom in the glow of the sun.',
	'The sun stretches across the sky, its warmth endless—let your hunger bloom like flowers kissed by its light.',
	'The day breathes warmth into the world, the air full of light—let each taste bloom in the warmth of the afternoon.',
];
const evening = [
	'What do you want for dinner?',
	'What do you want to eat?',
	'Have a good evening!',
	'Grab a bite to eat!',
	'Hungry night owl?',
	"Midnight munchies? We've got you!",
	'Evenings are for unwinding—and great food!',
	'The best part of your day? A delicious dinner!',
	"Make tonight's dinner the highlight of your day!",
	"Evening cravings? Let's turn them into dinner delights!",
	'After a long day, you deserve a feast!',
	'Dinner time—where cravings meet satisfaction!',
	'Dine like a star tonight—what are you in the mood for?',
	"The day's done—now it's time for a dinner victory!",
	"Evenings and comfort food go hand-in-hand—let's get started!",
	"As the sun fades, let your dinner be a celebration of the day's journey.",
	'In the twilight, let each taste linger like a soft memory, rich and deep.',
	'Beneath the evening sky, let your meal be a serenade to the night.',
	'The evening breeze whispers of rest—let dinner be your gentle companion.',
	'The night falls gently, and so does your hunger—let us satisfy it with something unforgettable.',
	'In the stillness of nightfall, let each bite be a promise of comfort and peace.',
	'As the world grows quiet, let your dinner speak the language of love and warmth.',
	'As the sun dips low, let your meal be a soft song that ends the day in harmony.',
	'In the embrace of twilight, let your dinner be a feast fit for the setting sun.',
	'The night sky unfurls its canvas—let your dinner paint the perfect end to your day.',
	'As the stars twinkle, let your meal be a constellation of flavors, guiding you to satisfaction.',
	'Let the nightfall carry you to a dinner that soothes, satisfies, and whispers goodnight.',
	'In the quiet moments of dusk, let each bite be a reminder of the peace the night can bring.',
	'The evening wraps you in its arms—let dinner be the warmth that completes its embrace.',
	'As the world quiets down, let your meal speak volumes of comfort and serenity.',
	'As the evening sky deepens, let each bite carry you into the peaceful arms of twilight.',
	'The sun has set, but your dinner is just beginning—what flavors will light up your night?',
	'As the stars begin to twinkle, let dinner be the shining moment that completes your day.',
	'The dusk settles gently—let your meal be the quiet comfort that follows.',
	"The evening unfolds softly—what are you craving for tonight's perfect dinner?",
	"As the day whispers its final farewell, let your meal be the first taste of evening's peace.",
	'With twilight in the air, let each bite bloom like a star lighting up the evening sky.',
	'The sun has dipped below the horizon—let dinner be the warmth that remains.',
	'The evening hums with quiet joy—let your meal be a symphony of comfort and flavor.',
	'The twilight casts its spell—let your dinner glow like the last light of the day.',
	'As the stars take their places, let each bite be a constellation of satisfaction.',
	'The day has done its work—let your meal be the well-deserved reward under the evening sky.',
	'In the quiet embrace of evening, let each flavor speak of rest and renewal.',
	'The night arrives softly—let your dinner be the gentle light that guides you through.',
	'As the world grows quiet, let each taste bloom like the first stars of nightfall.',
	"Evenings are for savoring—let tonight's dinner be the highlight of your day.",
	'The sun has left its final trace upon the sky—let dinner leave a lasting memory on your palate.',
	'The night whispers softly—what are you in the mood for as the stars wake?',
	'Let your dinner shine beneath the night sky, a beacon of warmth in the quiet.',
	'As the day fades, let your meal be the celebration that carries you into the stillness of night.',
	'Twilight wraps the world in serenity—what will you choose to savor this evening?',
	'The evening sky is a canvas painted with rest—let each taste be a brushstroke of peace.',
	'As the stars twinkle above, let your dinner be the light that fills your night.',
	'In the cool air of nightfall, let your cravings rise like a gentle breeze.',
	'The night calls for comfort—let each bite be the warmth that answers.',
	'The evening descends with grace—what will you choose to delight in tonight?',
	'As the sky turns to twilight, let each flavor unfold like a soft memory of the day.',
	'The stars are gathering—let your dinner be the feast that welcomes them.',
	'The night arrives with a whisper—what taste will you savor in the stillness?',
	'As the sun bows out, let your meal rise to meet the quiet of the evening.',
	'Let the calm of evening settle into every bite, bringing peace and comfort with each taste.',
	'The night sky holds its breath—let your meal breathe warmth and joy into the quiet.',
	'As dusk settles, let your hunger blossom like the stars that now fill the sky.',
	'In the serenity of nightfall, let each bite be a gentle reminder to pause and savor.',
	'The stars rise one by one—let each taste guide you into the restful embrace of night.',
];

const getGreeting = (hours: number) => {
	assert(bounded(hours, 0, 24));
	if (hours < 6) {
		return graveyard[Math.floor(Math.random() * graveyard.length)];
	}
	if (hours < 12) {
		return morning[Math.floor(Math.random() * morning.length)];
	}
	if (hours < 17) {
		return afternoon[Math.floor(Math.random() * afternoon.length)];
	}
	if (hours < 24) {
		return evening[Math.floor(Math.random() * evening.length)];
	}

	return 'Welcome to CMUEats!';
};

export default getGreeting;
