/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description If you have an active login session with cmueats, this will return your user info. (this is NOT intended to work cross-site) */
        get: operations["getWhoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The times array is guaranteed to be sorted and non-overlapping. Both start and end are inclusive boundaries */
        get: operations["getV2Locations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEmails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/locations/{locationId}/reviews/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getV2LocationsByLocationIdReviewsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/locations/{locationId}/reviews/stars/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putV2LocationsByLocationIdReviewsStarsMe"];
        post?: never;
        delete: operations["deleteV2LocationsByLocationIdReviewsStarsMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/locations/{locationId}/reviews/tags/{tagId}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putV2LocationsByLocationIdReviewsTagsByTagIdMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/locations/{locationId}/reviews/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getV2LocationsByLocationIdReviewsTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWhoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: ({
                            googleId: string;
                            id: number;
                            email: string;
                            firstName: (string | null) | null;
                            lastName: (string | null) | null;
                            pictureUrl: (string | null) | null;
                        } | null) | null;
                    };
                };
            };
        };
    };
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getV2Locations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        times: {
                            /** @example 1768074887682 */
                            start: number;
                            /** @example 1768074887682 */
                            end: number;
                        }[];
                        todaysSoups: {
                            name: string;
                            description: string;
                        }[];
                        todaysSpecials: {
                            name: string;
                            description: string;
                        }[];
                        name: (string | null) | null;
                        location: string;
                        shortDescription: (string | null) | null;
                        description: string;
                        url: string;
                        menu: (string | null) | null;
                        coordinateLat: (number | null) | null;
                        coordinateLng: (number | null) | null;
                        acceptsOnlineOrders: boolean;
                        id: string;
                        conceptId: (string | null) | null;
                    }[];
                };
            };
        };
    };
    getEmails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Alice */
                        name: string;
                        /** @example alice72@andrew.cmu.edu */
                        email: string;
                    }[];
                };
            };
        };
    };
    getV2LocationsByLocationIdReviewsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        starData: {
                            avg: (number | null) | null;
                            personalRating: (number | null) | null;
                            /**
                             * @example [
                             *       0,
                             *       1,
                             *       0,
                             *       4,
                             *       12,
                             *       4
                             *     ]
                             */
                            buckets: number[];
                        };
                        tagData: {
                            id: number;
                            name: string;
                            totalVotes: number;
                            totalLikes: number;
                            myReview: ({
                                vote: boolean;
                                text: (string | null) | null;
                                createdAt: number;
                                updatedAt: number;
                            } | null) | null;
                        }[];
                    };
                };
            };
        };
    };
    putV2LocationsByLocationIdReviewsStarsMe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    stars: number;
                };
                "application/x-www-form-urlencoded": {
                    stars: number;
                };
                "multipart/form-data": {
                    stars: number;
                };
            };
        };
        responses: never;
    };
    deleteV2LocationsByLocationIdReviewsStarsMe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    putV2LocationsByLocationIdReviewsTagsByTagIdMe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
                tagId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    voteUp?: boolean;
                    text?: string;
                };
                "application/x-www-form-urlencoded": {
                    voteUp?: boolean;
                    text?: string;
                };
                "multipart/form-data": {
                    voteUp?: boolean;
                    text?: string;
                };
            };
        };
        responses: never;
    };
    getV2LocationsByLocationIdReviewsTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        writtenReview: string;
                        tagName: string;
                        id: number;
                        tagId: number;
                        userId: number;
                        locationId: string;
                        vote: boolean;
                        createdAt: number;
                        updatedAt: number;
                    }[];
                };
            };
        };
    };
}
