import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';
import { QueryCache, QueryClient } from '@tanstack/react-query';
import type { paths } from './types/api'; // generated by openapi-typescript (see README for details)
import env from './env';
import notifySlack from './util/slack';
import locations from './mockLocations';

const BACKEND_LOCATIONS_URL = env.VITE_API_URL === 'local' ? '/' : `${env.VITE_API_URL}`;

export const fetchClient = createFetchClient<paths>({
    baseUrl: BACKEND_LOCATIONS_URL,
    fetch:
        env.VITE_API_URL === 'local'
            ? async (req) => {
                  if (!req.url.endsWith('/v2/locations')) return Response.json({}, { status: 404 });
                  return Response.json(locations, { status: 200 });
              }
            : (req) => fetch(req, { credentials: 'include' }),
});
export const queryClient = new QueryClient({
    defaultOptions: { queries: { staleTime: 120 * 1000 } },
    queryCache: new QueryCache({
        onError(error, query) {
            notifySlack(`<!channel> API ERROR! ${error}: ${query.queryKey.join('|')}`);
        },
    }),
});

export const $api = createClient(fetchClient);
export const login = () => {
    window.location.href = `${env.VITE_API_URL}/login?redirectURL=${window.location.origin}`; // not type safe, but we're probably not changing this either
};
export const logout = () => {
    window.location.href = `${env.VITE_API_URL}/logout?redirectURL=${window.location.origin}`; // not type safe, but we're probably not changing this either
};
