import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';
import { QueryClient } from '@tanstack/react-query';
import type { paths } from './types/api'; // generated by openapi-typescript (see README for details)
import env from './env';

const BACKEND_LOCATIONS_URL = env.VITE_API_URL === 'local' ? '/' : `${env.VITE_API_URL}`;

const fetchClient = createFetchClient<paths>({
    baseUrl: BACKEND_LOCATIONS_URL,
});
export const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 120 * 1000 } } });

export const $api = createClient(fetchClient);
