import { DateTime } from 'luxon';

const now = DateTime.now();
const earliestSunday = now.minus({ days: now.weekday % 7 }).startOf('day');
function toTimeSlotThisWeek({ day, hour, minute }: { day: number; hour: number; minute: number }) {
    return earliestSunday.plus({ day, hour, minute }).toMillis();
}
const locations = [
    {
        id: 82,
        name: 'TAHINI',
        shortDescription: 'Fresh Mediterranean, Certified Kosher Cuisine',
        description:
            'Tahini by Elegant Edge serves fresh, authentic Mediterranean cuisine, certified kosher by the Vaad Harabonim of Greater Pittsburgh. The menu features shawarma, vegan eggplant “shawarma” and falafel pita sandwiches, couscous and hummus bowls, and freshly prepared sides including grape leaves, Israeli chopped salad and zahtar pita fries. Offerings include a variety of plant-based and vegan options. Save time and order in advance for pick-up using Grubhub!',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/82',
        location: 'Resnik House, Tartans Pavilion',
        coordinates: { lat: 40.44260716039899, lng: -79.93995513782087 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 17, minute: 0 }, end: { day: 0, hour: 21, minute: 0 } },
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 14, minute: 0 } },
            { start: { day: 1, hour: 16, minute: 0 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 14, minute: 0 } },
            { start: { day: 2, hour: 16, minute: 0 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 14, minute: 0 } },
            { start: { day: 3, hour: 16, minute: 0 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 14, minute: 0 } },
            { start: { day: 4, hour: 16, minute: 0 }, end: { day: 4, hour: 21, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 14, minute: 0 } },
        ],
    },
    {
        id: 84,
        name: 'ZEBRA LOUNGE',
        shortDescription: 'hot and iced coffee and espresso drinks, pastries, sushi, bagels, pizza',
        description:
            'Nestled within the Great Hall of the College of Fine Arts, our trendy coffeehouse, Zebra Lounge, offers a diverse selection of treats. We brew locally roasted hot and cold Mechanic coffee and espresso drinks, teas, and cold beverages. Explore our wide selection of Vaad-certified kosher and Halal meals, including freshly baked pastries, hearthstone pizza, grab-and-go sandwiches and sushi, and a bagel bar, where you can choose from cream cheese, lox, and fresh vegetables. Zebra Lounge is ideal for starting your day with a delightful breakfast, enjoying a satisfying lunch, delving into an afternoon of focused study, or showcasing your artistic abilities, whether through song, music, or theater.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/84',
        location: 'College of Fine Arts, First Floor',
        coordinates: { lat: 40.44161664158368, lng: -79.94285872206078 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 16, minute: 0 } },
            { start: { day: 2, hour: 8, minute: 0 }, end: { day: 2, hour: 16, minute: 0 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 16, minute: 0 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 16, minute: 0 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 16, minute: 0 } },
        ],
    },
    {
        id: 91,
        name: 'EL GALLO DE ORO',
        shortDescription: 'Mexican cuisine, burritos and burrito bowls, tacos, quesadillas, salads',
        description:
            'El Gallo offers authentic Mexican cuisine – burritos and burrito bowls, tacos, quesadillas, and salads – made with fresh healthful ingredients. Dishes are prepared over the grill to maximize flavor and feature spices like cumin, cilantro, and chipotle.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/91',
        location: 'Cohon Center, Ground Floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/91/EG Full F25.pdf',
        coordinates: { lat: 40.44306965961788, lng: -79.94207835253889 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 12, minute: 0 }, end: { day: 0, hour: 20, minute: 0 } },
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 21, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 16, minute: 30 } },
            { start: { day: 6, hour: 12, minute: 0 }, end: { day: 6, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 92,
        name: 'THE EXCHANGE',
        shortDescription: 'Deli and breakfast sandwiches, daily hot entrées, grab-and-go.',
        description:
            'The Exchange offers custom deli sandwiches, soups, hot entrées, fresh baked goods, fruit, yogurt parfaits, snack and energy bars, and other grab-and-go items. The designated coffee bar includes hot brewed La Prima coffee, specialty and organic teas, cold beverages, and bottled juices.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/92',
        location: 'Posner Hall, 1st Floor',
        coordinates: { lat: 40.44144439971656, lng: -79.94195512801193 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 19, minute: 0 } },
            { start: { day: 2, hour: 8, minute: 0 }, end: { day: 2, hour: 19, minute: 0 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 19, minute: 0 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 19, minute: 0 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 18, minute: 0 } },
            { start: { day: 6, hour: 10, minute: 0 }, end: { day: 6, hour: 14, minute: 30 } },
        ],
        todaysSpecials: [
            { name: 'Chicken Finger Monday', description: 'with Macaroni and Cheese' },
            {
                name: 'Cavatappi Pasta in a Mild Garlic Cream Sauce with a Medley of Vegetables',
                description: 'Meatless Monday Pasta',
            },
        ],
        todaysSoups: [{ name: 'Tomato Soup', description: 'Great with Chicken fingers or Mac and Cheese' }],
    },
    {
        id: 94,
        name: 'LA PRIMA ESPRESSO',
        shortDescription: 'Italian-style coffee, espresso, matcha, tea, pastries, grab-and-go sandwiches and salads.',
        description:
            "Welcome to La Prima Espresso Company! We are a locally-owned coffee company focusing on Italian-style espressos and blends. All of our coffee is roasted to order in Pittsburgh's Manchester neighborhood on the North Side.In addition to espressos, cappuccinos, lattes, and other classic espresso + milk beverages, we also offer drip coffee, cold brew, nitro cold brew, matcha, chai, and hot and iced tea, as well as non-dairy options (oat, almond, and soy) and a variety of Monin flavored syrups (all gluten-free, nut-free, and certified kosher). Feeling hungry? We offer an assortment of delivered-daily sweet pastries from Mediterra Bakehouse. Enjoy a chocolate croissant, a cheese pocket, or cinnamon coffee cake muffin-- and more. Additionally, we source locally-made wraps, sandwiches, burritos, and croissants from Common Plea Catering. Some of our favorites include the chorizo breakfast burrito, the curried chickpea wrap (vegan!), and the turkey BLT wrap. Take La Prima home with you! We offer all the blends we serve on campus as whole bean 1 pound bags available for purchase. Have a question? Just ask a barista! We're ready and happy to serve you.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/94',
        location: 'Wean Hall, 5th Floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/94/LP Full F25.pdf',
        coordinates: { lat: 40.44259053115122, lng: -79.94597744494271 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 18, minute: 0 } },
            { start: { day: 2, hour: 8, minute: 0 }, end: { day: 2, hour: 18, minute: 0 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 18, minute: 0 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 18, minute: 0 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 18, minute: 0 } },
        ],
    },
    {
        id: 95,
        name: 'DE FER COFFEE & TEA AT RESNIK',
        shortDescription: 'Locally-roasted specialty coffee, tea, and scratch-made food',
        description:
            'De Fer Coffee & Tea serves locally-roasted specialty coffee and tea. Locally owned and operated by CMU alum, Atelier de Fer has been roasting coffee at its flagship store in Pittsburgh’s Strip District since 2017.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/95',
        location: 'Resnik House, DeFer',
        coordinates: { lat: 40.44239859745149, lng: -79.93978739035869 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 7, minute: 0 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 7, minute: 0 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 7, minute: 0 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 7, minute: 0 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 7, minute: 0 }, end: { day: 5, hour: 20, minute: 0 } },
            { start: { day: 6, hour: 9, minute: 0 }, end: { day: 6, hour: 17, minute: 0 } },
        ],
    },
    {
        id: 103,
        name: 'ENTROPY+',
        shortDescription: 'On-campus convenience store, serving snacks, grab-and-go meals, coffee, & more',
        description:
            'Entropy+ is the on-campus go-to spot for grocery items, health and beauty aids, bottled beverages, snacks, sweets, and local foods. In addition to their convenience products, Entropy+ carries a variety of grab-and-go meals: find hot and cold from our allergen-friendly kitchen Nourish, fresh-made sandwiches, salads, sushi, fresh fruits and veggies, and more.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/103',
        location: 'Cohon Center, Ground Floor',
        coordinates: { lat: 40.44294406631636, lng: -79.9421613966706 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 7, minute: 0 }, end: { day: 0, hour: 22, minute: 0 } },
            { start: { day: 1, hour: 7, minute: 0 }, end: { day: 1, hour: 22, minute: 0 } },
            { start: { day: 2, hour: 7, minute: 0 }, end: { day: 2, hour: 22, minute: 0 } },
            { start: { day: 3, hour: 7, minute: 0 }, end: { day: 3, hour: 22, minute: 0 } },
            { start: { day: 4, hour: 7, minute: 0 }, end: { day: 4, hour: 22, minute: 0 } },
            { start: { day: 5, hour: 7, minute: 0 }, end: { day: 5, hour: 20, minute: 0 } },
            { start: { day: 6, hour: 12, minute: 0 }, end: { day: 6, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 108,
        name: 'SCHATZ DINING ROOM',
        shortDescription: 'All-you-care-to-eat residential dining hall',
        description:
            "Schatz Dining Room is piloting all-you-care-to-eat lunchtime service for all community members, including undergraduate students.Schatz Dining Room offers campus's only all-you-care-to-eat residential dining room. Schatz serves breakfast, lunch and dinner, Monday - Friday, and brunch and dinner on the weekends. Breakfast and brunch offerings include cereal, fruit, egg dishes, breakfast meats, hot griddled items like pancakes and french toast, make-your-own waffles, and an avoiding gluten breakfast station and avoiding gluten options for lunch and dinner. Lunch and dinner include five stations serving a rotating menu of hot entrees, vegan and vegetarian options, soup and salad, made-to-order sandwiches, beverages and desserts. To make a reservation, please email schatzreservations@andrew.cmu.edu",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/108',
        location: 'Cohon Center, Second floor',
        coordinates: { lat: 40.44313373573427, lng: -79.94252833667237 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 10, minute: 30 }, end: { day: 0, hour: 14, minute: 30 } },
            { start: { day: 0, hour: 16, minute: 30 }, end: { day: 0, hour: 20, minute: 30 } },
            { start: { day: 1, hour: 7, minute: 30 }, end: { day: 1, hour: 10, minute: 0 } },
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 14, minute: 0 } },
            { start: { day: 1, hour: 16, minute: 30 }, end: { day: 1, hour: 20, minute: 30 } },
            { start: { day: 2, hour: 7, minute: 30 }, end: { day: 2, hour: 10, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 14, minute: 0 } },
            { start: { day: 2, hour: 16, minute: 30 }, end: { day: 2, hour: 20, minute: 30 } },
            { start: { day: 3, hour: 7, minute: 30 }, end: { day: 3, hour: 10, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 14, minute: 0 } },
            { start: { day: 3, hour: 16, minute: 30 }, end: { day: 3, hour: 20, minute: 30 } },
            { start: { day: 4, hour: 7, minute: 30 }, end: { day: 4, hour: 10, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 14, minute: 0 } },
            { start: { day: 4, hour: 16, minute: 30 }, end: { day: 4, hour: 20, minute: 30 } },
            { start: { day: 5, hour: 7, minute: 30 }, end: { day: 5, hour: 10, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 14, minute: 0 } },
            { start: { day: 5, hour: 16, minute: 30 }, end: { day: 5, hour: 20, minute: 30 } },
            { start: { day: 6, hour: 10, minute: 30 }, end: { day: 6, hour: 14, minute: 30 } },
            { start: { day: 6, hour: 16, minute: 30 }, end: { day: 6, hour: 20, minute: 30 } },
        ],
    },
    {
        id: 109,
        name: "THE GRILL AT SCOTTY'S",
        shortDescription: 'Freshly grilled entrees',
        description: 'Freshly-grilled items including burgers, shawarma, gyros, wraps and salads',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/109',
        location: 'Forbes Beeler Apartments, Servery',
        coordinates: { lat: 40.444127, lng: -79.939591 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 8, minute: 0 }, end: { day: 0, hour: 23, minute: 45 } },
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 23, minute: 45 } },
            { start: { day: 2, hour: 8, minute: 0 }, end: { day: 2, hour: 23, minute: 45 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 23, minute: 45 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 23, minute: 45 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 13, minute: 0 } },
            { start: { day: 5, hour: 14, minute: 0 }, end: { day: 5, hour: 23, minute: 45 } },
            { start: { day: 6, hour: 8, minute: 0 }, end: { day: 6, hour: 23, minute: 45 } },
        ],
    },
    {
        id: 110,
        name: 'HUNAN EXPRESS',
        shortDescription: 'Asian cuisine, rice bowls, boba/bubble tea, smoothies',
        description:
            'Authentic Chinese cuisine, featuring sauces made with bone broth, choose your base of noodles or rice and build your own meal with General Tso’s chicken, stir fry tofu, seasonal vegetables and pork ribs in black bean sauce. Braised fish, spring rolls, pork dumplings, red bean rice cakes are available daily. Enjoy fruit smoothies and build-your-own milk or fruit boba tea, with bubble toppings like tapioca, rainbow jelly, lychee jelly and popping boba.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/110',
        location: 'Newell-Simon Atrium',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/110/H Full F25.pdf',
        coordinates: { lat: 40.44326419955131, lng: -79.94551330831828 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 12, minute: 0 }, end: { day: 0, hour: 20, minute: 0 } },
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 113,
        name: 'AU BON PAIN AT SKIBO CAFÉ',
        shortDescription: 'Coffee/tea, espresso, soup, sandwiches/salads, grab-n-go, yogurt parfaits, fruit, snacks',
        description:
            'At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!Nutritional information can be found at aubonpain.com/nutrition.To place a catering order online, visit catering.aubonpain.com. To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com. For on-campus assistance, call 412-268-1054.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/113',
        location: 'Cohon Center, Second floor',
        coordinates: { lat: 40.44392022644891, lng: -79.94220130436851 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 7, minute: 0 }, end: { day: 0, hour: 21, minute: 0 } },
            { start: { day: 1, hour: 7, minute: 0 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 7, minute: 0 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 7, minute: 0 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 7, minute: 0 }, end: { day: 4, hour: 21, minute: 0 } },
            { start: { day: 5, hour: 7, minute: 0 }, end: { day: 5, hour: 21, minute: 0 } },
            { start: { day: 6, hour: 7, minute: 0 }, end: { day: 6, hour: 21, minute: 0 } },
        ],
    },
    {
        id: 114,
        name: 'TASTE OF INDIA',
        shortDescription: 'Taste of India provide a vibrant tastes of India.',
        description:
            "An Taste of  India restaurant typically offers a diverse menu featuring a variety of flavorful dishes from various regions of India. Expect aromatic spices, rich curries, tandoori specialties, and a range of vegetarian and non-vegetarian options. Whether you're a fan of  samosas, chicken curry, tandori chicken or butter chicken, Taste of India provide a vibrant tastes of India.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/114',
        location: 'Resnik House, Resnik Servery',
        coordinates: { lat: 40.44253705946464, lng: -79.9400539411368 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 16, minute: 30 }, end: { day: 0, hour: 21, minute: 0 } },
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 14, minute: 30 } },
            { start: { day: 1, hour: 16, minute: 30 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 14, minute: 30 } },
            { start: { day: 2, hour: 16, minute: 30 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 14, minute: 30 } },
            { start: { day: 3, hour: 16, minute: 30 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 14, minute: 30 } },
            { start: { day: 4, hour: 16, minute: 30 }, end: { day: 4, hour: 21, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 14, minute: 30 } },
            { start: { day: 5, hour: 16, minute: 30 }, end: { day: 5, hour: 21, minute: 0 } },
            { start: { day: 6, hour: 16, minute: 30 }, end: { day: 6, hour: 21, minute: 0 } },
        ],
    },
    {
        id: 115,
        name: 'ROHR CAFÉ  - LA PRIMA',
        shortDescription: "La Prima's second location on campus serving Italian-style coffee and food",
        description:
            "Welcome to La Prima Espresso Company! We are a locally-owned coffee company focusing on Italian-style espressos and blends. All of our coffee is roasted to order in Pittsburgh's Manchester neighborhood on the North Side.In addition to espressos, cappuccinos, lattes, and other classic espresso + milk beverages, we also offer drip coffee, cold brew, nitro cold brew, matcha, chai, and hot and iced tea, as well as non-dairy options (oat, almond, and soy) and a variety of Monin flavored syrups (all gluten-free, nut-free, and certified kosher). Stop by the brand new Rohr Cafe space on the 3rd floor of Gates! We have a fresh new layout and more food and beverage options than ever. Feeling hungry? We offer a variety of sandwiches and savory croissants available cold to-go or as a hot meal. Grab a selection from our food case and bring it to the counter-- we'll heat it for you on our panini presses. Some of these year's options include a turkey bacon, avocado and pepper jack breakfast sandwich, a spicy chorizo breakfast burrito, a Rueben sandwich on deli rye bread, and a hot Italian sausage roll-- all available as a hot meal for lunch or dinner. We offer an assortment of delivered-daily sweet pastries from Mediterra Bakehouse. Enjoy a chocolate croissant, a cheese pocket, or cinnamon coffee cake muffin-- and more. Additionally, we source locally-made wraps, sandwiches, burritos, and croissants from Common Plea Catering. Some of our favorites include the curried chickpea wrap (vegan!), the protein overnight oats, and the turkey BLT wrap. Take La Prima home with you! We offer all the blends we serve on campus as whole bean 1 pound bags available for purchase. Have a question? Just ask a barista! We're ready and happy to serve you.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/115',
        location: 'Gates Hillman Centers, Third floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/115/LP Full F25.pdf',
        coordinates: { lat: 40.44347617300122, lng: -79.94480928001676 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 9, minute: 0 }, end: { day: 0, hour: 16, minute: 0 } },
            { start: { day: 1, hour: 7, minute: 30 }, end: { day: 1, hour: 18, minute: 0 } },
            { start: { day: 2, hour: 7, minute: 30 }, end: { day: 2, hour: 18, minute: 0 } },
            { start: { day: 3, hour: 7, minute: 30 }, end: { day: 3, hour: 18, minute: 0 } },
            { start: { day: 4, hour: 7, minute: 30 }, end: { day: 4, hour: 18, minute: 0 } },
            { start: { day: 5, hour: 7, minute: 30 }, end: { day: 5, hour: 18, minute: 0 } },
            { start: { day: 6, hour: 9, minute: 0 }, end: { day: 6, hour: 16, minute: 0 } },
        ],
    },
    {
        id: 127,
        name: 'NOURISH',
        shortDescription: 'Order safe foods for those with dietary restrictions through Grubhub',
        description:
            'Nourish is an allergen-friendly kitchen with a menu prepared without gluten, wheat, milk, sesame, egg, soy, fish, shellfish, peanuts, and most tree nuts (except coconut). In addition to offering a diverse and delicious menu designed with everyone in mind, Nourish serves safe foods for our guests with dietary restrictions. Menu items include salads, sandwiches, hot entrees, and vegan offerings. All food is prepared and sealed in a dedicated kitchen by food service staff trained and highly knowledgeable about food allergens and cross-contact prevention. Students, faculty, and staff can download the Grubhub app to place orders. During operating hours, orders can be picked up at Nourish, located on the second floor of the Cohon Center near Rangos Ballroom. Grab-and-go items from Nourish are available at the following locations: Entropy+, Rothberg’s Roasters II, and Tepper Eatery. Items can be purchased individually or as a block meal for students using their meal plan. Orders for four or more people will take additional time to prepare when placed through Grubhub. We request that orders for larger groups (four or more) be placed 24 hours in advance through our catering department by emailing catering@andrew.cmu.edu or by phone at 412-268-2129.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/127',
        location: 'Cohon Center, Second floor',
        coordinates: { lat: 40.44296, lng: -79.941815 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 10, minute: 30 }, end: { day: 0, hour: 15, minute: 0 } },
            { start: { day: 0, hour: 15, minute: 30 }, end: { day: 0, hour: 18, minute: 0 } },
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 15, minute: 0 } },
            { start: { day: 1, hour: 15, minute: 30 }, end: { day: 1, hour: 18, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 15, minute: 0 } },
            { start: { day: 2, hour: 15, minute: 30 }, end: { day: 2, hour: 18, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 15, minute: 0 } },
            { start: { day: 3, hour: 15, minute: 30 }, end: { day: 3, hour: 18, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 15, minute: 0 } },
            { start: { day: 4, hour: 15, minute: 30 }, end: { day: 4, hour: 18, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 15, minute: 0 } },
            { start: { day: 5, hour: 15, minute: 30 }, end: { day: 5, hour: 18, minute: 0 } },
            { start: { day: 6, hour: 10, minute: 30 }, end: { day: 6, hour: 15, minute: 0 } },
            { start: { day: 6, hour: 15, minute: 30 }, end: { day: 6, hour: 18, minute: 0 } },
        ],
    },
    {
        id: 134,
        name: 'E.A.T. (EVENINGS AT TEPPER) - ROHR COMMONS',
        shortDescription: 'Dinner options at Tepper are Grubhub only!',
        description:
            'Offered on Grub-hub only, advanced ordering for pick-up in Rohr Commons. This quick service menu features build your own burgers and sandwiches, chicken tenders and fries, chicken quesadillas and entrée style salads.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/134',
        location: 'Tepper Building, 2nd Floor',
        coordinates: { lat: 40.44496677039454, lng: -79.94543510284873 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 16, minute: 30 }, end: { day: 1, hour: 19, minute: 30 } },
            { start: { day: 3, hour: 16, minute: 30 }, end: { day: 3, hour: 19, minute: 30 } },
            { start: { day: 4, hour: 16, minute: 30 }, end: { day: 4, hour: 19, minute: 30 } },
            { start: { day: 5, hour: 16, minute: 30 }, end: { day: 5, hour: 19, minute: 30 } },
        ],
    },
    {
        id: 136,
        name: "MILLIE'S COFFEE 'N' CREAMERY - ROHR COMMONS",
        shortDescription: 'Sustainably sourced coffee, ice cream, and vegan gelato.',
        description:
            "Pittsburgh-based Millie's Homemade Ice Cream is now scooping at CMU! Millie's first-ever Coffee 'n' Creamery serves chef-inspired ice creams, vegan gelatos, KLVN coffee and espresso drinks, Goodlander draft tea, and artisan pastries. Perfect for breakfast-on-the-go or an after-dinner sweet treat and everything in between. FLEX dollars, DineXtra, credit/debit and cash accepted!",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/136',
        location: 'Tepper Building, Second floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/136/MM Full F25.pdf',
        coordinates: { lat: 40.44497677044086, lng: -79.94526274161514 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 12, minute: 0 }, end: { day: 0, hour: 20, minute: 0 } },
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 22, minute: 0 } },
            { start: { day: 2, hour: 8, minute: 0 }, end: { day: 2, hour: 22, minute: 0 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 22, minute: 0 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 22, minute: 0 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 18, minute: 0 } },
            { start: { day: 6, hour: 12, minute: 0 }, end: { day: 6, hour: 18, minute: 0 } },
        ],
    },
    {
        id: 138,
        name: 'OLA OLA',
        shortDescription: 'Unique, hand-crafted signature sandwiches and smash burgers',
        description:
            'Bringing island vibes to CMU, Ola Ola Bowls serves up bold, Hawaiian-inspired flavors with a modern twist. Build your perfect Loco Moco Bowl starting with fluffy white rice, your choice of protein like Marinated Tofu Steak, Huli Huli Chicken, or a Halal Burger Patty. Then load up with vibrant toppings like kimchi, scallions, radish, and crunchy wonton strips! We’re also serving up Spam Musubi, indulgent Portuguese desserts, and cool, refreshing tropical drinks.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/138',
        location: 'Cohon Center, Second Floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/138/OO Full F25.pdf',
        coordinates: { lat: 40.44319390927541, lng: -79.9420529542194 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 21, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 21, minute: 0 } },
        ],
    },
    {
        id: 148,
        name: "STEPHANIE'S - MARKET C",
        shortDescription: 'Fresh sandwiches, wraps and salads, snacks, sweets, gourmet coffee and cold beverages',
        description:
            "Stephanie's - Market C provides fresh sandwiches, wraps, fruits, vegetables and salads so you can conveniently grab your lunch and go. Coupled with endless choices of snacks, ice cream, cold beverages and innovative coffee choices, this micro market has everything you're craving!Credit cards or Market C account cards are acceptable forms of payment. Dining plans, Flexible Dollars, DineXtra, and cash are not accepted at this location.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/148',
        location: 'Mellon Institute, Fourth Floor, Room 401',
        coordinates: { lat: 40.44618769931711, lng: -79.95093385349946 },
        acceptsOnlineOrders: false,
        times: [{ start: { day: 0, hour: 0, minute: 0 }, end: { day: 6, hour: 23, minute: 59 } }],
        todaysSpecials: [
            { name: 'Chicken Finger Monday', description: 'with Macaroni and Cheese' },
            {
                name: 'Cavatappi Pasta in a Mild Garlic Cream Sauce with a Medley of Vegetables',
                description: 'Meatless Monday Pasta',
            },
        ],
        todaysSoups: [{ name: 'Tomato Soup', description: 'Great with Chicken fingers or Mac and Cheese' }],
    },
    {
        id: 154,
        name: 'ROHR COMMONS - TEPPER EATERY',
        shortDescription: "Salad bar, homemade soup, and grab n' go",
        description:
            "The Tepper Eatery features a build-your-own salad bar, housemade soups, and other grab n' go eats. After 4 p.m on Fridays, the Tepper Eatery is only open for grab n' go and salad bar.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/154',
        location: 'Tepper Building, 2nd Floor Eatery',
        coordinates: { lat: 40.44493626367144, lng: -79.94534102575214 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 155,
        name: 'WILD BLUE SUSHI - RUGE ATRIUM',
        shortDescription: 'Fresh prepared sushi, hot rice bowls, bubble tea and coffee',
        description:
            "At Wild Blue, we craft fresh sushi daily using sustainably sourced seafood, made-to-order rice bowls and bubble teas. You can select from a wide variety of grab-and-options or request custom sushi, prepared on the spot. From rainbow rolls to poke bowls, Wild Blue has something for all sushi lovers. Choose from made-to-order orange chicken, teriyaki chicken or tofu rice bowls. We craft our menus with great respect for tradition, but our quality and sustainability standards keep us moving forward. We believe changing the world starts with us, and we're on a roll already. Our prepared foods may contain one, or a combination of, raw tuna, salmon, yellowtail, squid, octopus, fish roe, and/or other seafood. Consuming raw or undercooked meats, poultry, seafood, shellfish, or eggs may increase your risk of foodborne illness especially if you have certain medical conditions. Our prepared foods may have come into contact with one, or a combination of, the following known allergens: eggs, milk, fish, shellfish, peanuts, tree nuts, wheat, soybeans, or sesame.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/155',
        location: 'Scott Hall, Lower level',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/155/Wild Blue Sushi Menu 2025-2026.pdf',
        coordinates: { lat: 40.44269873724883, lng: -79.94664155857618 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 18, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 18, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 18, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 18, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 18, minute: 0 } },
        ],
    },
    {
        id: 168,
        name: 'TARTAN EXPRESS FOOD TRUCK',
        shortDescription: 'Chicken Tenders, French Fries, Sandwiches and Egg Rolls',
        description:
            'Enjoy hearty chicken tenders, specially-seasoned fries and delicious sandwiches at our campus food truck!',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/168',
        location: 'Legacy Plaza, Legacy Plaza',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/168/Tartan Express Menu.pdf',
        coordinates: { lat: 40.44283900428467, lng: -79.94133909281383 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 14, minute: 30 } },
            { start: { day: 1, hour: 16, minute: 30 }, end: { day: 1, hour: 20, minute: 30 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 14, minute: 30 } },
            { start: { day: 2, hour: 16, minute: 30 }, end: { day: 2, hour: 20, minute: 30 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 14, minute: 30 } },
            { start: { day: 3, hour: 16, minute: 30 }, end: { day: 3, hour: 20, minute: 30 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 14, minute: 30 } },
            { start: { day: 4, hour: 16, minute: 30 }, end: { day: 4, hour: 20, minute: 30 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 14, minute: 30 } },
            { start: { day: 5, hour: 16, minute: 30 }, end: { day: 5, hour: 20, minute: 30 } },
            { start: { day: 6, hour: 10, minute: 30 }, end: { day: 6, hour: 18, minute: 30 } },
        ],
    },
    {
        id: 173,
        name: 'FORBES AVENUE SUBS - ROHR COMMONS',
        shortDescription: 'Made-to-order deli-style subs and wraps. Vegan options available.',
        description:
            'Build your perfect sub or wrap at Forbes Ave., a deli-style eatery featuring fresh-sliced deli meat and cheeses.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/173',
        location: 'Tepper Building, 2nd Floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/173/FS Full 25.pdf',
        coordinates: { lat: 40.44490020783157, lng: -79.94540910407714 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 16, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 174,
        name: 'REVOLUTION NOODLE',
        shortDescription: 'Customizable Malatang Noodle bowls, from the owners of Hunan Express',
        description:
            'From the creators of Hunan Express comes one of Carnegie Mellon’s most beloved concepts, Revolution Noodle. Build your perfect Malatang noodle bowl with house-made broths, fresh noodles, seasonal vegetables, and various proteins. Don’t forget to add a savory bao bun, bubble tea, or fruit smoothie.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/174',
        location: 'Cohon Center, 2nd Floor, Marketplace',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/174/Revolution Noodle Menu 2025-2026.pdf',
        coordinates: { lat: 40.44336219896886, lng: -79.94196740444092 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 20, minute: 0 } },
            { start: { day: 6, hour: 12, minute: 0 }, end: { day: 6, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 178,
        name: 'THE EDGE CAFE & MARKET',
        shortDescription: 'Vaad-certified kosher bagels, pizza, bourekas & more!',
        description:
            'The Edge is a Vaad-certified kosher cafe and market. It serves freshly baked bagels, bagel sandwiches, Turkish bourekas, wraps, salads, pasta, and artisan pizzas baked in our hearthstone oven. It is located in Tartans Pavilion, overlooking Gesling Stadium.The Zebra Lounge serves pizza by the slice and Bourekas from The Edge.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/178',
        location: 'Resnik House',
        coordinates: { lat: 40.44265640089745, lng: -79.94021168805847 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 16, minute: 30 }, end: { day: 0, hour: 23, minute: 59 } },
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 23, minute: 59 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 23, minute: 59 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 23, minute: 59 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 23, minute: 59 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 14, minute: 0 } },
        ],
    },
    {
        id: 179,
        name: 'CAPITAL GRAINS - ROHR COMMONS',
        shortDescription: 'Student-run grain and salad bowl concept',
        description:
            'Capital Grains is a unique grain-and-salad bowl concept with a menu of whole grains, fresh vegetables, and vegetarian protein options. This first-of-its-kind student-run restaurant opens on the weekends and is committed to ensuring the highest quality food possible.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/179',
        location: 'Tepper Building, 2nd Floor, Rohr Commons Eatery',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/179/Capital Grains Menu F25.pdf',
        coordinates: { lat: 40.444658, lng: -79.945251 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 11, minute: 30 }, end: { day: 0, hour: 15, minute: 0 } },
            { start: { day: 6, hour: 11, minute: 30 }, end: { day: 6, hour: 15, minute: 0 } },
        ],
    },
    {
        id: 180,
        name: "SCOTTY'S MARKET BY SALEM'S",
        shortDescription: 'International and conventional groceries, savory grilled meats and hot meals.',
        description:
            "Scotty’s Market is CMU’s first campus grocery store! Operated by locally-owned Salem’s Market and Grill, who started their business 40 years ago in the heart of Oakland, Scotty’s Market is stocked with fresh produce, drinks, snacks, and international and conventional grocery items.The Grill at Scotty’s Market offers a wide selection of savory Mediterranean fare, including beef and lamb gyros, curries, sides, and breakfast sandwiches.  FLEX dollars, DineXtra, and credit and debit cards are accepted for grocery and grill items, and meal blocks can be used at the grill. Visit Salem's Grill at Scotty's Market for menus, specials and hours of operation. Scotty's Market is closed from 1 pm - 2 pm every Friday. Learn more about Salem's Market and Grill.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/180',
        location: 'Forbes Beeler Apartments, Forbes and Beeler',
        coordinates: { lat: 40.44414285761781, lng: -79.93888579754876 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 8, minute: 0 }, end: { day: 0, hour: 23, minute: 59 } },
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 12, minute: 0 } },
            { start: { day: 2, hour: 8, minute: 0 }, end: { day: 2, hour: 23, minute: 59 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 23, minute: 59 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 23, minute: 59 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 13, minute: 0 } },
            { start: { day: 5, hour: 14, minute: 0 }, end: { day: 5, hour: 23, minute: 59 } },
            { start: { day: 6, hour: 8, minute: 0 }, end: { day: 6, hour: 23, minute: 59 } },
        ],
    },
    {
        id: 184,
        name: 'CIAO BELLA',
        shortDescription: 'Customizable pasta plates',
        description:
            'Ciao Bella takes a globally inspired approach to pasta. Discover a menu of traditional dishes and customizable pasta bowls featuring international flavors.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/184',
        location: 'Cohon Center, 2nd Floor Marketplace',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/184/CB Full F25.pdf',
        coordinates: { lat: 40.4432203633545, lng: -79.94203823851873 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 185,
        name: 'TEPPER TAQUERIA',
        shortDescription: 'Mexican-style street tacos, burritos, quesadillas, bowls, and nachos',
        description:
            'Traditional, street-style tacos take the stage at Tepper Taqueria. Choose your style – taco, burrito, bowl, or nachos – from the make-your-own menu, and fill it with your choice of house-marinated meats (including a vegetarian, plant-based beef), rice and beans, and delicious, classic toppings.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/185',
        location: 'Tepper Building, Second Floor',
        coordinates: { lat: 40.44494190940949, lng: -79.94547335554091 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 19, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 16, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 19, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 19, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 16, minute: 0 } },
        ],
    },
    {
        id: 186,
        name: 'REDHAWK COFFEE',
        shortDescription: 'Local coffee roaster serving specialty coffee, tea, baked goods, and grab-and-go food.',
        description:
            'Redhawk Coffee is a local, family-owned coffee roasting company dedicated to serving the best specialty coffee on the market. With an approachable roast style and various drink options, Redhawk has an option for everyone. Try one of our fresh baked pastries from Driftwood Oven or even a matcha latte made with ceremonial grade matcha tea. Other popular options include mochas with Brunton’s chocolate milk and our signature honey-cinnamon latte.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/186',
        location: 'Scaife Hall, First Floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/186/RH Full F25.pdf',
        coordinates: { lat: 40.441808, lng: -79.947261 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 8, minute: 0 }, end: { day: 1, hour: 17, minute: 0 } },
            { start: { day: 3, hour: 8, minute: 0 }, end: { day: 3, hour: 17, minute: 0 } },
            { start: { day: 4, hour: 8, minute: 0 }, end: { day: 4, hour: 17, minute: 0 } },
            { start: { day: 5, hour: 8, minute: 0 }, end: { day: 5, hour: 17, minute: 0 } },
        ],
    },
    {
        id: 188,
        name: "STACK'D UNDERGROUND",
        shortDescription: 'Smashed burgers, Nashville-style chicken an gourmet grilled cheese',
        description:
            "Stack'd Underground is the newest restaurant concept from the Mero Restaurant Group. Combining signature dishes from the group's popular restaurants in Oakland. The menu includes smash’d burgers from Stack’d, Nashville chicken from CHiKN and gourmet grilled cheese from Melt’d. In addition to these best sellers the location will offer a selection of wraps, salads as well as a variety of vegetarian and halal options.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/188',
        location: 'Morewood Gardens, Lower level',
        menu: "https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/188/Melt'd[1].pdf",
        coordinates: { lat: 40.44538605085632, lng: -79.9430188095375 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 11, minute: 0 }, end: { day: 0, hour: 23, minute: 59 } },
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 23, minute: 59 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 23, minute: 59 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 23, minute: 59 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 23, minute: 59 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 23, minute: 59 } },
            { start: { day: 6, hour: 11, minute: 0 }, end: { day: 6, hour: 23, minute: 59 } },
        ],
    },
    {
        id: 190,
        name: "STACK'D DESSERT BAR",
        shortDescription: 'made-to-order milkshakes',
        description:
            "Cool down with a cold treat at the Stack'd Dessert Bar! Enjoy made-to-order milkshakes, sundaes, floats, banana splits and more.",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/190',
        location: 'Morewood Gardens, Lower Level',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/190/Dessert[1].pdf',
        coordinates: { lat: 40.44541493684331, lng: -79.94298366401661 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 11, minute: 0 }, end: { day: 0, hour: 23, minute: 59 } },
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 23, minute: 59 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 23, minute: 59 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 23, minute: 59 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 23, minute: 59 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 23, minute: 59 } },
            { start: { day: 6, hour: 11, minute: 0 }, end: { day: 6, hour: 23, minute: 59 } },
        ],
    },
    {
        id: 191,
        name: 'SHAKE SMART',
        shortDescription: 'Protein-packed smoothies, acai bowls and more!',
        description:
            'Shake Smart is a nutritious, health-forward smoothie and acai bowl concept.Their wide-ranging menu includes a mix of protein-packed shakes, fruit-forward smoothies, acaibowls, and more.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/191',
        location: 'Highmark Center for Health, Wellness and Athletics',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/191/SS Full.pdf',
        coordinates: { lat: 40.441244, lng: -79.941276 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 192,
        name: 'TEPPER TAQUERIA EXPRESS',
        shortDescription: "Authentic-inspired tacos, empanadas and more packaged for grab 'n’ go",
        description:
            "Tepper Taqueria Express, an extension of Tepper Taqueria, offers authentic-inspired eats packaged for grab' n’ go. This menu features empanadas, takeaway taco kits, churros, and more. Check out the weekly menu for a rotating special!",
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/192',
        location: 'Tepper Building, Second Floor',
        coordinates: { lat: 40.44494958989201, lng: -79.94541940780638 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 1, hour: 11, minute: 0 }, end: { day: 1, hour: 16, minute: 0 } },
            { start: { day: 2, hour: 11, minute: 0 }, end: { day: 2, hour: 16, minute: 0 } },
            { start: { day: 3, hour: 11, minute: 0 }, end: { day: 3, hour: 16, minute: 0 } },
            { start: { day: 4, hour: 11, minute: 0 }, end: { day: 4, hour: 16, minute: 0 } },
            { start: { day: 5, hour: 11, minute: 0 }, end: { day: 5, hour: 16, minute: 0 } },
        ],
    },
    {
        id: 193,
        name: 'CRISP AND CRUST',
        shortDescription: 'Fresh, made-to-order salads, flatbreads, and roll-ups',
        description:
            'Crisp and Crust is a greens-driven concept that takes salads and flatbreads to a new level, boasting a fully customizable menu along with some delicious signature dishes. The build-your-own menu will highlight ingredients like burrata and edamame, while signatures feature classics like the Caesar salad or Margherita Flatbread unique-to-CMU items like the Thai Crunch salad and Philly Cheesesteak Roll-up.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/193',
        location: 'Cohon Center, Marketplace, 2nd floor',
        menu: 'https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/193/CC Full F25.pdf',
        coordinates: { lat: 40.44326107687846, lng: -79.94202626834755 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 20, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 20, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 20, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 20, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 20, minute: 0 } },
        ],
    },
    {
        id: 194,
        name: 'SWEET PLANTAIN',
        shortDescription: 'Cuban-inspired pop-up lunch menu available through Grubhub only',
        description:
            'This Cuban-inspired menu features bold, traditional flavors. Enjoy Ropa Vieja, tender shredded beef in a rich tomato sauce, or Fricase de Pollo, creamy chicken stew—both served with yellow rice, black beans, and sweet plantains. The Picadillo a la Habanera blends ground beef, potatoes, raisins, olives, and capers for a savory-sweet delight, while the Vegetarian Bowl offers yuca, plantains, and Cuban staples. The Cubano-Style Sandwich combines turkey bacon, avocado, pickles, and zesty condiments in a crispy press. Sides include tangy Yuca con Mojo, sweet Platano Maduro Frito, and flavorful Arroz Amarillo con Frijoles.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/194',
        location: 'Resnik House, Tartans Pavilion, Tahini space',
        coordinates: { lat: 40.442613, lng: -79.939926 },
        acceptsOnlineOrders: true,
        times: [
            { start: { day: 0, hour: 16, minute: 30 }, end: { day: 0, hour: 21, minute: 0 } },
            { start: { day: 1, hour: 16, minute: 30 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 16, minute: 30 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 16, minute: 30 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 16, minute: 30 }, end: { day: 4, hour: 21, minute: 0 } },
        ],
    },
    {
        id: 201,
        name: "SALEM'S HOT BAR",
        shortDescription: 'Hot bar of ready-to-eat-delicacies',
        description: 'A fresh hot bar of rotating ready-to-eat delicacies.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/201',
        location: "Forbes Beeler Apartments, Scotty's Market",
        coordinates: { lat: 40.4441273, lng: -79.939591 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 10, minute: 30 }, end: { day: 0, hour: 22, minute: 0 } },
            { start: { day: 1, hour: 10, minute: 30 }, end: { day: 1, hour: 22, minute: 0 } },
            { start: { day: 2, hour: 10, minute: 30 }, end: { day: 2, hour: 22, minute: 0 } },
            { start: { day: 3, hour: 10, minute: 30 }, end: { day: 3, hour: 22, minute: 0 } },
            { start: { day: 4, hour: 10, minute: 30 }, end: { day: 4, hour: 22, minute: 0 } },
            { start: { day: 5, hour: 10, minute: 30 }, end: { day: 5, hour: 13, minute: 0 } },
            { start: { day: 5, hour: 14, minute: 0 }, end: { day: 5, hour: 22, minute: 0 } },
            { start: { day: 6, hour: 10, minute: 30 }, end: { day: 6, hour: 22, minute: 0 } },
        ],
    },
    {
        id: 202,
        name: 'FIRE AND STONE',
        shortDescription: 'Grilled Steaks, Fish and Wings',
        description: 'A great new location featuring steaks, fresh fish, sandwiches and wings.',
        url: 'https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/202',
        location: 'Resnik House, Resnik House',
        coordinates: { lat: 40.44253638019975, lng: -79.94032253558025 },
        acceptsOnlineOrders: false,
        times: [
            { start: { day: 0, hour: 16, minute: 30 }, end: { day: 0, hour: 21, minute: 0 } },
            { start: { day: 1, hour: 16, minute: 30 }, end: { day: 1, hour: 21, minute: 0 } },
            { start: { day: 2, hour: 16, minute: 30 }, end: { day: 2, hour: 21, minute: 0 } },
            { start: { day: 3, hour: 16, minute: 30 }, end: { day: 3, hour: 21, minute: 0 } },
            { start: { day: 4, hour: 16, minute: 30 }, end: { day: 4, hour: 21, minute: 0 } },
        ],
    },
].map((loc) => ({
    ...loc,
    coordinateLat: loc.coordinates.lat,
    coordinateLng: loc.coordinates.lng,
    times: loc.times.map(({ start, end }) => ({ start: toTimeSlotThisWeek(start), end: toTimeSlotThisWeek(end) })),
}));
export default locations;
