name: Lint
permissions:
    contents: read
on:
    push:
    pull_request:
        types: [opened, reopened, synchronize]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v6 # Setup pnpm
            - run: pnpm install
            - name: Check TypeScript
              run: pnpm tsc
            - name: Run Oxlint
              run: pnpm lint
            - name: Check formatting
              run: pnpm format:check
