name: Run unit tests
on:   
  push:
  pull_request:
    types: [opened, reopened]


jobs:
  lint:
    runs-on: ubuntu-latest
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - name: run vitest
        run: npm test